### ISSUE TITLE
Ship mesh missing texture

### ISSUE THREAD

**Issue by DieuDeGlace** [revenorror/Project-Atlas#10]
Using 7.0 of project atlas, upon going to a ship wreck located between khuul and urshilaku camp it seems to be missing textures on the dock. upon removal of the atlased shipwreck nif the problem is gone.

**Comment by revenorror** [comment]
Could you post exactly which mesh is this happening with? You can click on it with the console to get the ID. 
Does this happen with the dunmer ship found in city docks as well? Shipwrecks arent actually covered yet, just the normal boat.

**Comment by DieuDeGlace** [comment]
I take back what I said, I seem to have gotten the Ex_De_ShipWreck.nif file from morrowind optimization patch, instead of atlas. I knew it was from one of the two but I could've sworn I originally saw it hiding in atlas. I apologize
