### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by benjaminwinger** [revenorror/Project-Atlas#15]
There's an issue with the atlas generators I would be interested in fixing, but I can't do that without this repository, or at least the atlas generator scripts, having some sort of licence (otherwise, you're not giving permission for anyone to make modifications).

See https://choosealicense.com/no-permission/ (https://choosealicense.com/ also has a licence guide).

Or is this project not accepting contributions?

**Comment by revenorror** [comment]
Thank you for the offer to contribute. The repo has been officially Unlicensed
