### ISSUE TITLE
Player can fall through the imperial architecture platform

### ISSUE THREAD

**Issue by AbduSharif** [revenorror/Project-Atlas#7]
Use the save from here:
https://gitlab.com/OpenMW/openmw/-/issues/6331

Make sure atlas is installed then travel from Raven Rock to the Fort.

ex_imp_plat_01

**Comment by revenorror** [comment]
I've known about some people having this issue but I've never been able to replicate it myself.
- Just to clarify, did you install AtlAd as well, or only Project Atlas?
- Does this still happen without mods? 
It would probably to best if you could upload your version of that mesh so I can give it a look too.

**Comment by revenorror** [comment]
Thanks for the help! I'll just go ahead and redo the mesh from vanilla, I have no idea what's causing this.
