### ISSUE TITLE
flora_emp_parasol

### ISSUE THREAD

**Issue by MwGek** [revenorror/Project-Atlas#9]
The parasol Project atlas mesh is made from an ugly subdived mesh and not vanilla. Also the bark has a mirror seam in the UV and the bark can be added to the top mushroom atlas if rotated 90 degrees. So this is a reminder to basicly redo the mesh somewhere in the future or temporary remove it from Project Atlas altogether.

**Comment by revenorror** [comment]
Fixed! Bark is still a separate shape since the emp parasols may end up getting merged into the Telvanni atlas if I figure out what do do with that thing
